# Generated by Django 4.2.15 on 2026-08-25 13:52

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def copy_existing_client_photos(apps, schema_editor):
    Client = apps.get_model("client", "Client")
    ClientProfilePicture = apps.get_model("client", "ClientProfilePicture")
    rows = [
        ClientProfilePicture(
            client_id=client.id,
            picture=client.picture,
            is_current=True,
        )
        for client in Client.objects.exclude(picture__isnull=True).exclude(picture="")
    ]
    ClientProfilePicture.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0012_rename_email_id_client_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientProfilePicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    cloudinary.models.CloudinaryField(
                        max_length=255,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="client_uploads",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded at"),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, verbose_name="Is Current Picture"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_pictures",
                        to="client.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Profile Picture",
                "verbose_name_plural": "Client Profile Pictures",
                "db_table": "client_pictures",
                "ordering": ["-uploaded_at", "-id"],
            },
        ),
        migrations.RunPython(copy_existing_client_photos, migrations.RunPython.noop),
    ]
