# Generated by Django 4.2.15 on 2026-09-28 20:05

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_client_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='branch',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('organization', 'Organization')], default='individual', max_length=20, verbose_name='Client type'),
        ),
        migrations.AddField(
            model_name='client',
            name='current_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='employment_sector',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='employment_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='group_chairperson',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='group_member_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='group_objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='group_savings_cycle_months',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='client',
            name='group_secretary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='group_treasurer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='highest_education_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='minimum_savings_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='client',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='next_of_kin_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='UG'),
        ),
        migrations.AddField(
            model_name='client',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='occupation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='client',
            name='referred_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='savings_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('irregular', 'Irregular')], max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='savings_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='services_interested',
            field=models.TextField(blank=True, verbose_name='Services interested in'),
        ),
        migrations.AddField(
            model_name='client',
            name='village',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='client',
            name='workplace',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$', message='Enter a valid email address.')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile_telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region='UG', verbose_name='Mobile Telephone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='reg_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Reg. No'),
        ),
    ]
