# Generated by Django 4.2.15 on 2026-09-28 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0018_client_joint_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegistrationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('step', models.PositiveSmallIntegerField(default=0)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('photo_name', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
