# Generated by Django 4.2.15 on 2026-09-29 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0019_clientregistrationdraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('workbook', models.BinaryField(null=True)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('result', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('reg_number')), name='client_import_reg_idx'),
        ),
        migrations.AddField(
            model_name='clientimportjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
